### ISSUE TITLE
Model trained using darkflow( tiny_yolo_voc ), when converted to graph, no objects are detected.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [fernandodelacalle/yolo-darkflow-movidius#1]
I trained a model with tiny-yolo-voc.weights to detect number plates. The training was done using Darkflow. The detection work's fine with .pb and .meta files. Then I compiled, the .pb file to generate the graph file(My ncsdk is installed in an aws ec2 instance). After obtaining Inference using the graph.queue_inference_with_fifo_elem( ) method , I referred your work ( https://github.com/fernandodelacalle/yolo-darkflow-movidius/blob/master/detection_camera.py, https://github.com/fernandodelacalle/yolo-darkflow-movidius/blob/8a2c07878e98fe370c72f8a6e951041fbb5093c0/yolo_utils.py ) for generating bbox from graph's output. But no boxes were detected. Does that mean it is not possible or is there any mistakes I'm making?

[ Edit ]
The problem was with my pre-processing. I thought resizing and adding an extra dimension will do. Since that doesn't worked,I gave your pre-processing method a try. That worked.

**Comment by tomriddle54** [comment]
Did you train your own model @Sreerag-ibtl is it possible to detect custom objector to run on movidius

**Comment by Sreerag-ibtl** [comment]
@syedmustafa54 Yes, I trained a custom object detector using tiny yolo and was able to run it on movidius.
